class Main {
    public static void main(String[] args) {
        try {
            int[] array = new int[5];
            array[5] = 30 / 0;  // This line will throw an exception
        } 
        catch (ArithmeticException | ArrayIndexOutOfBoundsException e) {
            System.out.println("An exception occurred: " + e.getMessage());
        } 
        System.out.println("Rest of the code...");
    }
}
